version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_cs403
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs403
      MYSQL_USER: mai
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - d:/docker_data/mysql_cs403:/var/lib/mysql
    networks:
      - cs403_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cs403
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - cs403_network

networks:
  cs403_network:
    driver: bridge
